[project]
name = "iac-learn"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
  "awscli-local>=0.22.2",
  "pyright>=1.1.408",
  "pytest>=9.0.2",
  "ruff>=0.15.2",
  "terraform-local>=0.11.1",
]
